// <auto-generated />
namespace NgTodoList.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Alterado_relacao_todo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alterado_relacao_todo));
        
        string IMigrationMetadata.Id
        {
            get { return "201410312051439_Alterado_relacao_todo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
